# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json
PackageIdentifier: sm516.BRO
PackageVersion: 1.0.0
PackageLocale: ja-JP
Publisher: sm516
PublisherUrl: https://github.com/sm516-london1957/BRO
PackageName: BRO
PackageUrl: https://github.com/sm516-london1957/BRO
ShortDescription: Neon Table styleの対戦ゲーム「BRO」
Description: 日本語フォントと効果音を同梱した、raylib製の対戦ゲームです。
License: Proprietary
ManifestType: defaultLocale
ManifestVersion: 1.10.0
